language: python
python:
- 3.5
script:
- python setup.py build
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: OovZ0/toixiQVov7trRHpGiBy2ZmJH8B+lQGPC1SalK0rRvC/tayNOcyV+a2a2FXNfum5SMLF7lowOc9oYjMRJIvR5pNEUn8J9T/hcpDSBmZ6sB0hQ+E5VpbUjAnlt+v9qdriFehcGNBSgedPe+Q9e2/NfLL4tNAH+u/u50l7LoawMp5R2JeWc7HvYDEY0McwQS6ssQJM+ZqGLyketacO1z5HqnwrwrVWiVu5IFV+6sbUZrc+5M+87W3pTxVfz5wAUZd5kL8SHiUu0dttzgxtRIykv0iage+z6LQ1vg0fWFOT+zTBZl94FIekU9xkG1n5W2ZfUifph3aUkXQxyG2Bw+0I3QSKw8EJHkNjJ9zLxXNdHgiejAOTrbVNlz2rxxMQhbxOjh9d4EtwX9rfTqMHgVNEwFKRsc1wOZILnmiIclgYhQtQvhYrA7fRBQfEO3lr03rl7c+Tqi/q1OsC6SkWNYK0US9/BrArAvjpsZC7CeIs8ig6gju6QSTRh4TfkZXUjHgp27TVdHcq9XTzrf0iCKXs2CVBV+TZJHtRBdY+2VyqzH+pE6fPwKAiq0bOYomL6OnATlMTUr45pUt+c3DPbnwNdrzdxSKpM98//rD2zddupZpxZ6o2HkE8tlN70Gh0O3Crkwi3ws6T/gDj9qYZSgZEMFMfIkWj6vfhpzbioE=
  on:
    tags: true
    repo: ovh/python-logging-ldp
