language: python
python:
- 3.5
script:
- python setup.py build
deploy:
  provider: pypi
  user: cdumay
  password:
    secure: bFhMjsRMYnA8pGWKU2+NA9dOvRS5+PVayueZRbhqDa6OB3NrIHuytpnHgVprl49T8pXGH3AvbZdqjTPQL0gnnmvG+sgWS7b5TSgKP++gC+9DKnMKOstz74+/3UNrsgU2JexkbocA8tpjtFjE9rcuOt01FOCazlkX/1sReiuXZSQRTXbuq4GFxAMz6TOyJZWoxYVOWg8M+n4v59qDwviVoPjG38nhKWU3qr5rLBir5yxi6yPz5KecIubZjQueesA/45glCaDc/wkmC8Tt8TwokMNeNa/WUFr3NmDaw1ri1z+cseU358f4PSzXPDMOuNJIJHTO/hEFczOEh8CGycxLhkl6EY4lijLJENM0EzsI3iCQvkUALPYz88tjRHDiDnXgQ3k3VxCXklbX98QJCxMlYQsQWOLxI4B9J5A3aH2ioGKBSHLyw009TgAu08Ce3BQjKjvY1dmG86jRu9h5QtvW59qmG4T20JGo6m/EW4BKl21rdekUiW7iiincB1LjxZxUvE6DbSWLoxaPdcGln04/v4wMKWdDDsn5wO0Ih7MHzKdVzvB4r7qz7DsjJozEYLX6+OWtDfrr2CpR0hMNlxSYEJwXHUj90R5Q09X0iZ6ySfqFuA0KEHAYP2ya0XPgJ4kkZXFMfmoc1G8AIa6LTH9vXXKSqM83JGGFqR/Es7OIKIQ=
  on:
    tags: true
    repo: ovh/python-logging-ldp
